name: my_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  cupertino_icons: ^1.0.6
  algoliasearch: ^1.41.1
  appwrite: ^20.3.2
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  font_awesome_flutter: ^10.12.0
  go_router: ^17.0.0
  google_fonts: ^6.3.2
  intl: ^0.20.2
  url_launcher: ^6.3.0
  provider: ^6.0.5
  file_picker: ^10.3.7
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
